version: '3.8'

services:
  steamapi:
    build:
      context: ..
      dockerfile: docker/steamapi.dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SteamApi__ApiKey=${STEAM_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 