version: '3.8'

services:
  steamapi:
    build:
      context: ..
      dockerfile: docker/steamapi.dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped 