name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    branches: [ main, develop ]
    paths:
      - 'src/SteamApi/**'
      - 'docker/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Determine tags
      id: tags
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/steam-api-dotnet:${{ github.event.release.tag_name }},${{ secrets.DOCKERHUB_USERNAME }}/steam-api-dotnet:latest" >> $GITHUB_OUTPUT
        else
          echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/steam-api-dotnet:${{ github.ref_name }},${{ secrets.DOCKERHUB_USERNAME }}/steam-api-dotnet:latest" >> $GITHUB_OUTPUT
        fi
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/steamapi.dockerfile
        push: true
        tags: ${{ steps.tags.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 